web_client/src/components/Collapse/index.tsx
web_client/src/components/DocumentInput/existingDocTab.tsx
web_client/src/components/DocumentInput/index.tsx
web_client/src/components/DocumentInput/types.tsx
web_client/src/components/DocumentInput/wikiUploadTab.tsx
web_client/src/pages/Sessions/index.tsx

Responsive Sessions/Documents page

---

web_client/src/components/RecitalBox/index.tsx
web_client/src/components/RecitalBox/useControleCallback.ts
web_client/src/components/RecitalBox/useDocumentNavigation.ts
web_client/src/components/RecitalBox/useKeyboardControl.ts

Recording interface - Touch devices support

---

server/models/recital_session.py
server/routers/crud/utils.py
server/routers/sessions.py
web_client/src/pages/Sessions/index.tsx
web_client/src/types/document.ts
web_client/src/types/session.ts

Show document title in sessions list

---

server/models/text_document.py
server/routers/api.py
server/routers/crud/utils.py
server/routers/documents.py
server/routers/sessions.py
web_client/src/client/common.ts
web_client/src/client/documents.ts
web_client/src/client/queries/documents.ts
web_client/src/client/sessions.ts
web_client/src/components/DocumentInput/existingDocTab.tsx
web_client/src/components/DocumentInput/index.tsx
web_client/src/hooks/documents/index.ts

Public Document Library - Server API support

---

web_client/src/components/RecitalBox/index.tsx

Only apply autostop on active recording sessions

---

server/engines/extraction_engine.py
server/managers/document_manager.py
server/models/text_document.py
server/requirements.txt
server/routers/documents.py
web_client/src/components/RecitalBox/index.tsx

Server API - Support plaintext / html text document uploads

---

web_client/src/components/RecitalBox/useControleCallback.ts

Web UI - BugFix - Next sentence at the end when not recording - should do nothing

---

server/engines/aggregation_engine.py
server/managers/recital_manager.py
web_client/src/components/RecitalBox/SessionFinalizeModal.tsx
web_client/src/components/RecitalBox/index.tsx

Late users know they need to wait for all data to upload
Fixes #28

Late-to-upload audio segments might be missed during finalization

---

web_client/src/components/RecitalBox/Header.tsx
web_client/src/components/RecitalBox/index.tsx
web_client/src/components/RecitalBox/useDocumentNavigation.ts

Store&Recall location within a read text document between recording sessions

---

web_client/src/components/RecitalBox/useDocumentNavigation.ts

Web UI - document navigation will not go down to first sentence

---

server/engines/aggregation_engine.py

Subtitle generation Bug - Ms should not be truncated

---

web_client/src/components/SessionPreview/subTrackingPreview.tsx
web_client/src/locales/he/recordings.json
web_client/src/locales/yi/recordings.json
web_client/src/pages/Sessions/index.tsx

Web UI - Preview tracks subtitles

---

web_client/src/components/RecitalBox/index.tsx
web_client/src/hooks/recodingUploader/capture.ts
web_client/src/hooks/textSegmentUploader/index.ts
web_client/src/utils/index.ts

Web UI - Bug fix - Sentence out-of-order upload - basic queue impl.

---

server/managers/recital_manager.py
server/resource_access/recitals_ra.py

Fixes #53
Now ensuring time base is UTC in delta calcs

Server - Bug - Incomplete final recordings

---

server/managers/document_manager.py
server/routers/documents.py
web_client/src/client/documents.ts
web_client/src/components/DocumentInput/freeTextUploadTab.tsx
web_client/src/components/DocumentInput/index.tsx
web_client/src/hooks/documents/index.ts
web_client/src/locales/he/documents.json
web_client/src/locales/yi/documents.json

Text Document Upload - Add more methods

---

server/managers/recital_manager.py
server/resource_access/stats_ra.py
server/routers/stats.py
server/utility/cache/stats.py
web_client/src/client/queries/stats.ts
web_client/src/client/stats.ts
web_client/src/components/RecitalBox/HeaderUserStats.tsx
web_client/src/components/RecitalBox/SessionFinalizeModal.tsx
web_client/src/components/RecitalBox/index.tsx
web_client/src/components/SessionDelete/useSessionDelete.ts
web_client/src/components/SystemTotalStats/index.tsx
web_client/src/pages/Leaderboard/index.tsx
web_client/src/pages/Login/index.tsx
web_client/src/types/stats.ts

Calculate and present "Total Recorded - All Users" stats

---

web_client/src/components/RecitalBox/SessionInfoBox.tsx
web_client/src/components/SessionPreview/subTrackingPreview.tsx
web_client/src/components/TablePager/index.tsx

Use custom subtitles preview component from recording interface

---

server/engines/extraction_engine.py

Server - Text Processing - Remove text in parentheses from Uploaded docs.

---

web_client/src/components/RecitalBox/index.tsx
web_client/tailwind.config.ts

Web UI - Incrase read text color contrast

---

web_client/src/components/RecitalBox/Header.tsx
web_client/src/components/RecitalBox/SessionInfoBox.tsx
web_client/src/components/RecitalBox/index.tsx

Web UI - Improve recording layout on small-screen devices

---

server/configuration.py
server/routers/web_client.py
web_client/src/client/queries/help.ts
web_client/src/locales/he/translation.json
web_client/src/locales/yi/translation.json
web_client/src/pages/Help/faqSection.tsx
web_client/src/pages/Help/index.tsx

Simple FAQ Page (Managed in Wordpress)

---

web_client/src/components/MicCheck/index.tsx
web_client/src/hooks/recodingUploader/index.ts

Web UI - Request mic permissions only when needed

---

web_client/src/components/RecitalBox/index.tsx

After saving "sin last sentence" - set next recording at omitted sentence

---

server/resource_access/stats_ra.py
web_client/src/components/LeaderboardTable/index.tsx
web_client/src/locales/he/recordings.json
web_client/src/locales/yi/recordings.json
web_client/src/types/stats.ts

Add "How much to climb the leaderboard" stat
